fix #511 not complete
pycontw/pycon.tw pull request #1083
Opened 2022-06-17 13:53 UTC by Ritabear

## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ x] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
**Describe what the change is**
You don't need to explain HOW you change the code. Your code, including comments in the code should explicitly
self-describe enough about how you change the code.
排order，但回傳的時候別回傳order，而是後台排好。

## Steps to Test This Pull Request
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

到Sponsor 的model 新增order=models.IntegerField(....) 
後台admin新增欄位
到view.py order_by 新增 'order' ----> order_by('level', 'order') 

## Expected behavior
A clear and concise description of what you expected to happen.
回傳的API會依廠商相同地位照著order自己排好

## Related Issue
If applicable, refernce to the issue related to this pull request.
#511 

## More Information
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. You may also want to refer
to [how to wirte the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)

2022-06-17 13:54 UTC, Ritabear commented
@mattwang44 
麻煩你看看了 ><

2022-06-17 16:31 UTC, mattwang44 requested changes

2022-06-17 16:31 UTC, mattwang44 commented on src/sponsors/models.py
> +    )
- `max_length` will not take any effect for the numeric field. If you'd like to constrain the range of the value, use [`validators`](https://docs.djangoproject.com/en/dev/ref/validators/#maxvaluevalidator) instead.
- Would using only positive value make more sense? (e.g. use `PositiveIntegerField` instead)
- IMO it's not easy to realize the purpose of this field simply by its name. Consider adding `help_text` here.
- What happened if there is any sponsor instance with this field to be null? Would it be at the start or the end of the returned list (and is that what you expected)?

2022-06-18 15:03 UTC, Ritabear commented
@mattwang44  修改了~ 請幫我看看，感謝你！

2022-07-23 14:55 UTC, Ritabear commented
@mattwang44 
修改好了~~ 麻煩matt看一下

2022-07-24 15:24 UTC, mattwang44 approved these changes
LGTM

加了一個 commit 是補 `order` 欄位在 admin site 上的翻譯

p.s. 自動產出 po 檔案的指令為
```
docker exec -it pycontw_dev sh -c "cd src && ./manage.py makemessages -l zh_Hant -l en_US"
```

2022-07-24 15:25 UTC, merged