Feat/1119
pycontw/pycon.tw pull request #1122
Opened 2023-02-27 11:07 UTC by Ritabear

## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [ ] **New feature**
- [X] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
**Describe what the change is**
You don't need to explain HOW you change the code. Your code, including comments in the code should explicitly
self-describe enough about how you change the code.
1. rename migrations(del willing_to)
2. rename some columns, having the string "willing_to" 
3. add `choices.py` 
4. move the string from `core/models.py` to `core/choices.py` ( the string  = `CATEGORY_CHOICES`) 
5. For i18n, I make the commend `makemessages`.

## Steps to Test This Pull Request
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
6. Scroll down to '....'
7. See error

## Expected behavior
A clear and concise description of what you expected to happen.

## Related Issue
If applicable, refernce to the issue related to this pull request.

## More Information
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. You may also want to refer
to [how to wirte the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)

2023-03-01 03:24 UTC, josix requested changes

2023-03-01 03:24 UTC, josix commented on src/locale/en/LC_MESSAGES/django.po
> +# This file is distributed under the same license as the PACKAGE package.
**question:** Is this file redundant? We're using lang-code `en-us` instead of `en`. I guess this translation file is not being used.

2023-03-01 03:24 UTC, josix commented on src/core/models.py
> +from .choices import CATEGORY_CHOICES
**nitpick (non-blocking):** If you have time, please consider adding other  options group such as [LANGUAGE_CHOICES](https://github.com/pycontw/pycon.tw/blob/4f9e349caf253fd8488a96aa28af315e9a4f2964/src/core/models.py#L94), [PYTHON_LVL_CHOICES](https://github.com/pycontw/pycon.tw/blob/4f9e349caf253fd8488a96aa28af315e9a4f2964/src/core/models.py#L111), [RECORDING_POLICY_CHOICES](https://github.com/pycontw/pycon.tw/blob/4f9e349caf253fd8488a96aa28af315e9a4f2964/src/core/models.py#L111), etc. to the `chloices.py` file, thanks!

2023-03-08 13:45 UTC, mattwang44 commented on src/locale/zh_Hant/LC_MESSAGES/django.po
> +#: proposals/forms/mixins.py:133
這行是不小心貼上的嗎？英文翻譯也有

2023-03-08 14:11 UTC, Ritabear commented on src/locale/zh_Hant/LC_MESSAGES/django.po
> +#: proposals/forms/mixins.py:133
這行是自動產出的@@

2023-03-08 14:41 UTC, closed without merging