feat: add code cov on github actions
pycontw/pycon.tw pull request #1129
Opened 2023-03-07 06:06 UTC by baby230211

## Types of changes

- [ ] **Bugfix**
- [ x ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
move code cov to github actions

2023-03-07 06:11 UTC, josix requested changes

2023-03-07 06:11 UTC, josix commented on .github/workflows/ci.yaml
>      # TODO: Use Official Codecov from Github Actions
**nitpick:** Need to remove this.

2023-03-07 06:17 UTC, baby230211 commented on .github/workflows/ci.yaml
>      # TODO: Use Official Codecov from Github Actions
fixed ~ thanks

2023-03-07 08:23 UTC, mattwang44 commented on .github/workflows/ci.yaml
> +        pytest -n 2 --cov=. --cov-report=xml
這樣只會有 report file 但 terminal 上就不會有，但希望之後打開 github action log 還是能看的到 report

2023-03-07 14:55 UTC, baby230211 commented on .github/workflows/ci.yaml
> +        pytest -n 2 --cov=. --cov-report=xml
updated~

2023-03-08 00:41 UTC, mattwang44 approved these changes
Nice job! Only one last minor issue left.

2023-03-08 00:41 UTC, mattwang44 commented on .github/workflows/ci.yaml
>      - name: Run Test and Codecov
```suggestion
    - name: Run Test
```

2023-03-08 10:02 UTC, josix approved these changes

2023-03-08 10:02 UTC, merged