chore: rm CI requirements
pycontw/pycon.tw pull request #1130
Opened 2023-03-08 07:17 UTC by mattwang44

## Types of changes

- [ ] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [x] **Other (please describe)**: CI requirements file is excessive after adopting github action

## Description

The CI requirements file is almost the same as the dev requirements file. Let CI also install from the latter and the latter one can be deleted safely.

2023-03-08 10:04 UTC, josix commented
我記得 `ci.txt` 是 @iknowright 上次加進來的，再麻煩後續幫忙 review，感謝🙇🏻‍♂️

2023-03-08 13:13 UTC, iknowright requested changes
Thanks.
補充一下：
原本在用 Travis 的時候是需要 `ci.txt` (原名叫做 `travis.txt`) , 在還沒有導入 codecov github actions 之前還是需要這個檔案，現在 master 有導入了  github codecov ， 需要 rebase 一下 action 才會過，不然現在 action 跑起來是缺 codecov 的。

2023-03-08 13:38 UTC, mattwang44 commented
I know, that's why it's still a draft XD

2023-03-19 13:00 UTC, iknowright approved these changes

2023-03-19 13:02 UTC, merged