Put keynote slides
pycontw/pycon.tw pull request #946
Opened 2020-09-20 08:18 UTC by Maliaotw

## Types of changes

- [ ] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
put keynote slides url to file

2020-09-20 10:49 UTC, uranusjr approved these changes

2020-09-21 14:45 UTC, yychen commented
Wait wait... @Maliaotw 你只是把 json 加了這個欄位但是前端 template 好像不會秀阿 orz

2020-09-24 06:15 UTC, Maliaotw commented
修正了， 請在幫我看看

2020-10-02 06:17 UTC, yychen requested changes
另外，就是你的 IDE 好像都會把整個縮排做處理，其實這樣就會很難看得出你到底實際上改的是哪些地方 orz

2020-10-02 06:17 UTC, yychen commented on src/templates/pycontw-2020/contents/_default/conference/keynotes.html
> +						</article>
你這樣的話，第一是那一整個 tab 會很空，第二個是沒有投影片的人這邊就會點下去是空白的...

我在想，你有沒有辦法把他簡單的做，加在 "演講" 的那個 tab 的內容裡，但是變成很像 social links 那樣，如果有投影片，就放在最下面，例如
```html
  {% if data.slides %}
	 <div class="slides">
		  Slides: <a href="{{ data.slides }}" target="_blank" rel="noopener">{{ data.slides}}</a>
	 </div>
  {% endif %}
```

2020-12-29 15:51 UTC, tai271828 commented
@Maliaotw is this merge request ready to review? If no, you may convert this pr to "draft" (this is a github feature). If yes, please signal us.

2020-12-29 17:26 UTC, mattwang44 commented
@tai271828 Yes, this PR is done and is currently under review by me. However, since this PR (& also #782) is a part of the 2020 website, I personally wish Tom to be the final reviewer. It's my fault to make it being stale for so long since Tom & I haven't kicked-off the handover tasks until tomorrow (we'll have a meeting in person and go through the checklist for closing the 2020 website). So, please give us more time, and we'll close this PR soon 😅.

2020-12-30 06:49 UTC, tai271828 commented
@mattwang44 no problem! I asked to make sure this PR is in people's radar, so we won't waste @Maliaotw 's contribution : )

2021-01-11 14:35 UTC, yychen approved these changes
ㄜ! 這跟我預期的不太一樣，但這樣子也是可以的啦 orz.

2021-01-11 14:36 UTC, merged