feat(sponsors/models.py): Migrate the images of sponsors' logo to GCS
pycontw/pycon.tw pull request #987
Opened 2021-03-09 03:07 UTC by hsuanchi

## Types of changes
- [ ] **Bugfix**
- [ ] **New feature**
- [x] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
The images of the sponsors' logos are previously uploaded manually to the GCE server via Django admin. However, not every sponsor team member has access. 

- images -> Store in a dedicated GCS bucket
- Django -> Takes in the GCS path of each image

-> Sponsor team only needs the GCS IAM policy to update the logos

https://trello.com/c/TKTeVtlI/17-migrate-the-images-of-sponsors-logo-to-gcs

## Steps to Test This Pull Request
Steps to reproduce the behavior:
1. Go to Django Admin.
2. Create Sponsor.
3. if in dev environment -> the sponsor logo image will be save in local folder.
4. if in production env ->  the sponsor logo image will be save in google cloud storage.

2021-03-09 03:25 UTC, mattwang44 commented
CI failed due to the credential file is not uploaded (& it shouldn't be)

2021-03-09 04:45 UTC, mattwang44 commented on src/sponsors/models.py
> +        storage= default_storage if settings.DEBUG else GoogleCloudStorage(),
Adopting the `settings.DEBUG` as the switch to determine whether to use `GoogleCloudStorage` leads to the discrepancy of migration scripts in dev & production environments, which should cause pain when trying to deploy a new version.

2021-03-11 03:06 UTC, mattwang44 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate the images of sponsors' logo to GCS](https://trello.com/c/TKTeVtlI/17-migrate-the-images-of-sponsors-logo-to-gcs)

2021-03-31 01:42 UTC, kaka-lin commented
Remember rebase to new master

2021-03-31 03:33 UTC, hsuanchi commented
Done :)

2021-04-01 02:06 UTC, kaka-lin commented
> Done :)

2021-04-01 02:48 UTC, mattwang44 commented
Why we close this PR?

2021-04-01 02:54 UTC, kaka-lin commented
> Why we close this PR?

My mistake, I pressed the wrong button

2021-04-04 04:06 UTC, setmao requested changes

2021-04-04 04:06 UTC, setmao commented on src/sponsors/models.py
> +from django.conf import settings
Group these package and order them like:
```python
from storages.backends.gcloud import GoogleCloudStorage

from django.conf import settings
from django.core.files.storage import default_storage
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.translation import override
from django.utils.text import slugify

from core.models import ConferenceRelated, BigForeignKey
```

2021-04-04 17:40 UTC, mattwang44 commented
@hsuanchi @setmao 
I've opened a new PR #999 for upgrading Django. @hsuanchi please help to drop the commits for upgrading Django in this PR.

2021-04-06 06:18 UTC, hsuanchi commented
> @hsuanchi @setmao
> I've opened a new PR #999 for upgrading Django. @hsuanchi please help to drop the commits for upgrading Django in this PR.

Done :D

2021-04-08 12:09 UTC, setmao approved these changes
LGTM

2021-04-13 03:56 UTC, merged