feat(sponsors/models.py): Add a new field of sponsor subtitle
pycontw/pycon.tw pull request #990
Opened 2021-03-17 09:55 UTC by hsuanchi

## Types of changes

- [ ] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
- Add a new field for sponsor subtitle (e.g. `連續N年贊助`)
  - support zh/en
  - the data needs to be accessed via [API](https://github.com/pycontw/pycon.tw/blob/master/src/sponsors/views.py#L21)
  - ref: [the field of sponsor intro](https://github.com/pycontw/pycon.tw/blob/master/src/sponsors/models.py#L26_L28)

https://trello.com/c/vICfFVL6/31-add-a-new-field-of-sponsor-subtitle

## Steps to Test This Pull Request
1. Go to Django Admin.
2. Create Sponsor.

2021-03-26 17:43 UTC, kaka-lin reviewed
LGTM!

Remember rebase to new master

2021-03-29 06:14 UTC, hsuanchi commented
> LGTM!
> 
> Remember rebase to new master

Done, Thanks!

2021-03-30 02:57 UTC, setmao requested changes

2021-03-30 02:57 UTC, setmao commented on src/sponsors/translation.py
> +    fields = ('intro','subtitle',)
Typo, missing whitespace after ‘,'

2021-03-31 03:16 UTC, hsuanchi commented on src/sponsors/translation.py
> +    fields = ('intro','subtitle',)
Done, Thanks!

2021-04-01 02:56 UTC, setmao approved these changes
LGTM！

2021-04-01 02:57 UTC, merged